services:
  traefik:
    image: "traefik:v3.4"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
    ports:
      - "443:443"
      - "8085:80"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - main-network
  wordpress:
    build:
      context: ./wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${WEBSITE_DB_NAME}
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      # Get the routes from http
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.routers.wordpress.rule=HostRegexp(`.`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
    networks:
      - main-network
  redis:
    image: redis:6
    restart: always
    logging:
      # Configure the logs retention according to your needs
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    # launch Redis in cache mode with :
    #  - max memory up to 50% of your RAM if needed (--maxmemory 512mb)
    #  - deleting oldest data when max memory is reached (--maxmemory-policy allkeys-lru)
    entrypoint:
      [
        "redis-server",
        "--maxmemory",
        "512mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]
    networks:
      - main-network
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${WEBSITE_DB_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
    networks:
      - main-network

volumes:
  wordpress:
  db:
networks:
  main-network:
    driver: bridge
